#ifndef COMMAND_METADATA_H
#define COMMAND_METADATA_H

#include <array>
#include <string_view>

struct CommandMetadata {
    std::string_view abbreviation;
    std::string_view expanded;
};

constexpr std::array COMMAND_REGISTRY = {
    CommandMetadata{"AI", "AUTO INFORMATION"},
    CommandMetadata{"AT", "ANTENNA TUNER"},
    CommandMetadata{"BY", "BUSY"},
    CommandMetadata{"CN", "CTCSS NUMBER"},
    CommandMetadata{"CT", "CTCSS"},
    CommandMetadata{"DC", "DESTINATION CODE"},
    CommandMetadata{"DI", "DCS ID"},
    CommandMetadata{"DN", "DOWN"},
    CommandMetadata{"DS", "DCS"},
    CommandMetadata{"FA", "FREQUENCY VFO A"},
    CommandMetadata{"FB", "FREQUENCY VFO B"},
    CommandMetadata{"FN", "FUNCTION"},
    CommandMetadata{"HD", "SCAN HOLD"},
    CommandMetadata{"ID", "ID"},
    CommandMetadata{"IF", "INFORMATION"},
    CommandMetadata{"LK", "LOCK"},
    CommandMetadata{"LO", "LOCAL"},
    CommandMetadata{"LT", "AUTO LOCK TUNE"},
    CommandMetadata{"MC", "MEMORY CHANNEL"},
    CommandMetadata{"MD", "MODE"},
    CommandMetadata{"MR", "MEMORY READ"},
    CommandMetadata{"MS", "MEMORY SCAN"},
    CommandMetadata{"MT", "MUTE"},
    CommandMetadata{"MW", "MEMORY WRITE"},
    CommandMetadata{"OS", "OFFSET"},
    CommandMetadata{"RC", "RIT CLEAR"},
    CommandMetadata{"RD", "RIT DOWN"},
    CommandMetadata{"RU", "RIT UP"},
    CommandMetadata{"RT", "RIT"},
    CommandMetadata{"RX", "RX"},
    CommandMetadata{"SC", "SCAN"},
    CommandMetadata{"SH", "SLOPE TUNE HIGH"},
    CommandMetadata{"SL", "SLOPE TUNE LOW"},
    CommandMetadata{"SM", "S-METER (SUB)"},
    CommandMetadata{"SP", "SPLIT"},
    CommandMetadata{"ST", "STEP"},
    CommandMetadata{"TN", "TONE NUMBER"},
    CommandMetadata{"TO", "TONE"},
    CommandMetadata{"TX", "TX"},
    CommandMetadata{"UP", "UP"},
    CommandMetadata{"VB", "VBT"},
    CommandMetadata{"VR", "VOICE RECALL"},
    CommandMetadata{"XT", "XIT"},
    CommandMetadata{"ZZ", "NOT A COMMAND"},
};

enum class CommandPrefixEnum {
    AI,
    AT,
    BY,
    CN,
    CT,
    DC,
    DI,
    DN,
    DS,
    FA,
    FB,
    FN,
    HD,
    ID,
    IF,
    LK,
    LO,
    LT,
    MC,
    MD,
    MR,
    MS,
    MT,
    MW,
    OS,
    RC,
    RD,
    RU,
    RT,
    RX,
    SC,
    SH,
    SL,
    SM,
    SP,
    ST,
    TN,
    TO,
    TX,
    UP,
    VB,
    VR,
    XT,
    ZZ
};

#endif
