#ifndef COMMANDS_H
#define COMMANDS_H

#include "command_prefix.h"
#include "command_base.h"
#include "command_switch.h"
#include "ai.h"
#include "at.h"
#include "di.h"
#include "dn.h"
#include "ds.h"
#include "hd.h"
#include "id.h"
#include "if.h"
#include "lk.h"
#include "lo.h"
#include "ms.h"
#include "rd.h"
#include "rc.h"
#include "rt.h"
#include "ru.h"
#include "rx.h"
#include "sc.h"
#include "sp.h"
#include "st.h"
#include "to.h"
#include "tx.h"
#include "up.h"
#include "vr.h"
#include "xt.h"

#endif